[tox]
envlist = py310,py311,py312,py313,codestyle,dist-check,security
skip_missing_interpreters = True

[testenv]
deps =  -r {toxinidir}/test-requirements.txt

commands = pytest -v tests/
recreate = true

[testenv:codestyle]
deps =
    ruff
    isort
commands =
    ruff check src/ tests/
    ruff format --check src/ tests/
    isort --check-only src/ tests/

[testenv:dist-check]
deps =
    twine
    build
commands =
    python -m build --outdir {distdir}
    twine check {distdir}/*

[testenv:security]
deps =
    bandit

; ignoring errors
commands =
    - bandit -r src/slackv3/
